 local menub98be87cb7dd79b1aae28d118dbf9f72 = {
     {"Onboard", "onboard", "/usr/share/icons/hicolor/16x16/apps/onboard.png" },
 }

 local menud51ff67768edbb1ac85d6f654b29a1f1 = {
     {"Drumstick Drum Grid", "drumstick-drumgrid", "/usr/share/icons/hicolor/16x16/apps/drumstick.png" },
     {"Drumstick MIDI Player", "drumstick-guiplayer ", "/usr/share/icons/hicolor/16x16/apps/drumstick.png" },
     {"Drumstick Virtual Piano", "drumstick-vpiano", "/usr/share/icons/hicolor/16x16/apps/drumstick.png" },
     {"GNU Solfege", "solfege", "/usr/share/pixmaps/solfege.svg" },
     {"LibreOffice Math", "libreoffice --math ", "/usr/share/icons/hicolor/16x16/apps/libreoffice-math.png" },
     {"VMPK", "vmpk", "/usr/share/icons/hicolor/16x16/apps/vmpk.png" },
 }

 local menu63909e8219db0bcede147cb7926a07fa = {
     {"Dokumentenbetrachter", "evince "},
     {"Kalender", "gnome-calendar"},
     {"Kontakte", "gnome-contacts"},
     {"LibreOffice", "libreoffice ", "/usr/share/icons/hicolor/16x16/apps/libreoffice-startcenter.png" },
     {"LibreOffice Base", "libreoffice --base ", "/usr/share/icons/hicolor/16x16/apps/libreoffice-base.png" },
     {"LibreOffice Calc", "libreoffice --calc ", "/usr/share/icons/hicolor/16x16/apps/libreoffice-calc.png" },
     {"LibreOffice Draw", "libreoffice --draw ", "/usr/share/icons/hicolor/16x16/apps/libreoffice-draw.png" },
     {"LibreOffice Impress", "libreoffice --impress ", "/usr/share/icons/hicolor/16x16/apps/libreoffice-impress.png" },
     {"LibreOffice Math", "libreoffice --math ", "/usr/share/icons/hicolor/16x16/apps/libreoffice-math.png" },
     {"LibreOffice Writer", "libreoffice --writer ", "/usr/share/icons/hicolor/16x16/apps/libreoffice-writer.png" },
     {"Minder", "/usr/bin/flatpak run --branch=stable --arch=x86_64 --command=com.github.phase1geo.minder --file-forwarding com.github.phase1geo.minder @@  @@", "/var/lib/flatpak/exports/share/icons/hicolor/16x16/apps/com.github.phase1geo.minder.svg" },
     {"Minder", "com.github.phase1geo.minder ", "/var/lib/flatpak/exports/share/icons/hicolor/16x16/apps/com.github.phase1geo.minder.svg" },
     {"Wörterbuch", "xfce4-dict", "/usr/share/icons/hicolor/16x16/apps/org.xfce.Dictionary.png" },
     {"x42-mixtri", "x42-mixtri", "/usr/share/icons/hicolor/256x256/apps/x42-mixtri.png" },
 }

 local menu9356bc29cbd145b1b330eaeb7614fd1e = {
     {"Boxen", "gnome-boxes "},
     {"CMake", "cmake-gui ", "/usr/share/icons/hicolor/32x32/apps/CMakeSetup.png" },
     {"Code - OSS", "/usr/bin/code-oss --no-sandbox --unity-launch ", "/usr/share/pixmaps/com.visualstudio.code.oss.png" },
     {"Cuttlefish", "cuttlefish"},
     {"Electron", "electron ", "/usr/share/pixmaps/electron.png" },
     {"Electron 11", "electron11 ", "/usr/share/pixmaps/electron11.png" },
     {"Electron 12", "electron12 ", "/usr/share/pixmaps/electron12.png" },
     {"Emacs", "emacs ", "/usr/share/icons/hicolor/16x16/apps/emacs.png" },
     {"FLUID", "fluid ", "/usr/share/icons/hicolor/32x32/apps/fluid.png" },
     {"GdaBrowser", "gda-browser-5.0", "/usr/share/pixmaps/gda-browser-5.0.png" },
     {"Glade", "glade "},
     {"Globaler Plasma-Designexplorer", "lookandfeelexplorer"},
     {"Icon Browser", "yad-icon-browser", "/usr/share/icons/hicolor/16x16/apps/yad.png" },
     {"Micro", "xterm -e micro "},
     {"Minder", "/usr/bin/flatpak run --branch=stable --arch=x86_64 --command=com.github.phase1geo.minder --file-forwarding com.github.phase1geo.minder @@  @@", "/var/lib/flatpak/exports/share/icons/hicolor/16x16/apps/com.github.phase1geo.minder.svg" },
     {"Minder", "com.github.phase1geo.minder ", "/var/lib/flatpak/exports/share/icons/hicolor/16x16/apps/com.github.phase1geo.minder.svg" },
     {"Plasma-Datenquellen-Betrachter", "plasmaengineexplorer"},
     {"Plasma-Designexplorer", "plasmathemeexplorer"},
     {"PyCharm Community Edition", "/usr/bin/pycharm ", "/usr/share/pixmaps/pycharm.png" },
     {"Qt Assistant", "assistant", "/usr/share/icons/hicolor/32x32/apps/assistant.png" },
     {"Qt Designer", "designer ", "/usr/share/icons/hicolor/128x128/apps/QtProject-designer.png" },
     {"Qt Linguist", "linguist ", "/usr/share/icons/hicolor/16x16/apps/linguist.png" },
     {"Qt QDbusViewer ", "qdbusviewer", "/usr/share/icons/hicolor/32x32/apps/qdbusviewer.png" },
     {"Scratch", "scratch", "/usr/share/icons/hicolor/32x32/apps/scratch.png" },
     {"SuperCollider IDE", "scide ", "/usr/share/pixmaps/sc_ide.svg" },
     {"Unity", "/usr/bin/unity-editor", "/usr/share/icons/hicolor/256x256/apps/unity-editor-icon.png" },
     {"Unity Hub", "unityhub", "/usr/share/pixmaps/unityhub.png" },
     {"UserFeedback-Konsole", "UserFeedbackConsole"},
     {"VSCodium", "/usr/share/vscodium-bin/bin/codium --no-sandbox --unity-launch ", "/usr/share/pixmaps/vscodium.png" },
     {"ipython", "xterm -e ipython", "/usr/share/pixmaps/ipython.png" },
 }

 local menue64b29f9c504872c202fabd746ddbf8a = {
     {"Adobe Flash Player Standalone", "/usr/bin/flashplayer"},
     {"Aseprite", "aseprite ", "/usr/share/icons/hicolor/32x32/apps/aseprite.png" },
     {"Bildbetrachter", "gpicview ", "/usr/share/icons/hicolor/48x48/apps/gpicview.png" },
     {"Bildbetrachter", "eog "},
     {"Bildschirmfoto", "lximage-qt --screenshot"},
     {"Blender", "blender "},
     {"Dokument-Scanner", "simple-scan"},
     {"Dokumentenbetrachter", "evince "},
     {"GNU Image Manipulation Program", "gimp-2.10 ", "/usr/share/icons/hicolor/16x16/apps/gimp.png" },
     {"Gpick", "gpick ", "/usr/share/icons/hicolor/48x48/apps/gpick.png" },
     {"Inkscape", "inkscape ", "/usr/share/icons/hicolor/16x16/apps/org.inkscape.Inkscape.png" },
     {"Krita", "krita ", "/usr/share/icons/hicolor/16x16/apps/krita.png" },
     {"LXImage", "lximage-qt ", "/usr/share/icons/hicolor/48x48/apps/lximage-qt.png" },
     {"LibreOffice Draw", "libreoffice --draw ", "/usr/share/icons/hicolor/16x16/apps/libreoffice-draw.png" },
     {"Ristretto-Bildbetrachter", "ristretto ", "/usr/share/icons/hicolor/16x16/apps/org.xfce.ristretto.png" },
     {"ScreenGrab", "screengrab", "/usr/share/icons/hicolor/32x32/apps/screengrab.png" },
     {"XDvi", "xdvi "},
     {"gThumb", "gthumb ", "/usr/share/icons/hicolor/16x16/apps/org.gnome.gThumb.png" },
 }

 local menuc8205c7636e728d448c2774e6a4a944b = {
     {"Avahi SSH-Server-Browser", "/usr/bin/bssh"},
     {"Avahi VNC-Server-Browser", "/usr/bin/bvnc"},
     {"Chromium", "/usr/bin/chromium ", "/usr/share/icons/hicolor/16x16/apps/chromium.png" },
     {"Discord", "/usr/bin/discord", "/usr/share/pixmaps/discord.png" },
     {"Ein verbundenes Gerät mit KDE Connect öffnen", "kdeconnect-handler --open "},
     {"FileZilla", "filezilla", "/usr/share/icons/hicolor/16x16/apps/filezilla.png" },
     {"Firefox", "/usr/lib/firefox/firefox ", "/usr/share/icons/hicolor/16x16/apps/firefox.png" },
     {"Google Chrome (unstable)", "/usr/bin/google-chrome-unstable ", "/usr/share/icons/hicolor/16x16/apps/google-chrome-unstable.png" },
     {"HexChat", "hexchat --existing ", "/usr/share/icons/hicolor/48x48/apps/hexchat.png" },
     {"KDE Connect", "kdeconnect-app"},
     {"KDE Connect-SMS", "kdeconnect-sms"},
     {"KDE-Connect-Anzeige", "kdeconnect-indicator"},
     {"Steam (Native)", "/usr/bin/steam-native ", "/usr/share/icons/hicolor/16x16/apps/steam.png" },
     {"Steam (Runtime)", "/usr/bin/steam-runtime ", "/usr/share/icons/hicolor/16x16/apps/steam.png" },
     {"TeamViewer", "/opt/teamviewer/tv_bin/script/teamviewer", "/usr/share/icons/hicolor/16x16/apps/TeamViewer.png" },
     {"TigerVNC-Betrachter", "/usr/bin/vncviewer", "/usr/share/icons/hicolor/16x16/apps/tigervnc.png" },
     {"Transmission", "transmission-gtk ", "/usr/share/pixmaps/transmission.png" },
     {"Verbindungen", "gnome-connections"},
     {"Web", "epiphany "},
 }

 local menu1c312514bc584128c5392d361470b415 = {
     {"x42-darc", "x42-darc", "/usr/share/icons/hicolor/256x256/apps/x42-darc.png" },
     {"x42-dpl", "x42-dpl", "/usr/share/icons/hicolor/256x256/apps/x42-dpl.png" },
     {"x42-fat1", "x42-fat1", "/usr/share/icons/hicolor/256x256/apps/x42-fat1.png" },
     {"x42-fil4", "x42-fil4"},
     {"x42-matrixmixer8x8", "x42-matrixmixer8x8", "/usr/share/icons/hicolor/256x256/apps/x42-matrixmixer8x8.png" },
     {"x42-meter 1/3 Octave Spectrum Analyzer", "x42-meter 15", "/usr/share/icons/hicolor/256x256/apps/x42-meter.png" },
     {"x42-meter BBC M-6", "x42-meter 5", "/usr/share/icons/hicolor/256x256/apps/x42-meter.png" },
     {"x42-meter BBC Meter (Stereo)", "x42-meter 4", "/usr/share/icons/hicolor/256x256/apps/x42-meter.png" },
     {"x42-meter Bit Meter", "x42-meter 18", "/usr/share/icons/hicolor/256x256/apps/x42-meter.png" },
     {"x42-meter DIN Meter (Stereo)", "x42-meter 6", "/usr/share/icons/hicolor/256x256/apps/x42-meter.png" },
     {"x42-meter DR-14 - Crest Factor Loudness Range Meter", "x42-meter 11", "/usr/share/icons/hicolor/256x256/apps/x42-meter.png" },
     {"x42-meter EBU Meter (Stereo)", "x42-meter 7", "/usr/share/icons/hicolor/256x256/apps/x42-meter.png" },
     {"x42-meter EBU R128 Meter", "x42-meter 0", "/usr/share/icons/hicolor/256x256/apps/x42-meter.png" },
     {"x42-meter Goniometer", "x42-meter 13", "/usr/share/icons/hicolor/256x256/apps/x42-meter.png" },
     {"x42-meter K12/RMS Meter (Stereo)", "x42-meter 3", "/usr/share/icons/hicolor/256x256/apps/x42-meter.png" },
     {"x42-meter K14/RMS Meter (Stereo)", "x42-meter 2", "/usr/share/icons/hicolor/256x256/apps/x42-meter.png" },
     {"x42-meter K20/RMS Meter (Stereo)", "x42-meter 1", "/usr/share/icons/hicolor/256x256/apps/x42-meter.png" },
     {"x42-meter Nordic Meter (Stereo)", "x42-meter 8", "/usr/share/icons/hicolor/256x256/apps/x42-meter.png" },
     {"x42-meter Phase/Frequency Wheel", "x42-meter 14", "/usr/share/icons/hicolor/256x256/apps/x42-meter.png" },
     {"x42-meter Signal Distribution Histogram", "x42-meter 17", "/usr/share/icons/hicolor/256x256/apps/x42-meter.png" },
     {"x42-meter Stereo Phase-Correlation Meter", "x42-meter 12", "/usr/share/icons/hicolor/256x256/apps/x42-meter.png" },
     {"x42-meter Stereo/Frequency Scope", "x42-meter 16", "/usr/share/icons/hicolor/256x256/apps/x42-meter.png" },
     {"x42-meter Surround Level 8", "x42-meter 19", "/usr/share/icons/hicolor/256x256/apps/x42-meter.png" },
     {"x42-meter True-Peak and RMS Meter (Stereo)", "x42-meter 10", "/usr/share/icons/hicolor/256x256/apps/x42-meter.png" },
     {"x42-meter VU Meter (Stereo)", "x42-meter 9", "/usr/share/icons/hicolor/256x256/apps/x42-meter.png" },
     {"x42-scope", "x42-scope", "/usr/share/icons/hicolor/256x256/apps/x42-scope.png" },
     {"x42-spectr", "x42-spectr", "/usr/share/icons/hicolor/256x256/apps/x42-spectr.png" },
     {"x42-stepseq", "x42-stepseq", "/usr/share/icons/hicolor/256x256/apps/x42-stepseq.png" },
     {"x42-tuna Instrument Tuner", "x42-tuna 0", "/usr/share/icons/hicolor/256x256/apps/x42-tuna.png" },
     {"x42-tuna Instrument Tuner (Spectrum)", "x42-tuna 1", "/usr/share/icons/hicolor/256x256/apps/x42-tuna.png" },
     {"zamautosat", "ZamAutoSat"},
     {"zamaximx2", "ZaMaximX2"},
     {"zamcomp", "ZamComp"},
     {"zamcompx2", "ZamCompX2"},
     {"zamdelay", "ZamDelay"},
     {"zamdynamiceq", "ZamDynamicEQ"},
     {"zameq2", "ZamEQ2"},
     {"zamgate", "ZamGate"},
     {"zamgatex2", "ZamGateX2"},
     {"zamgeq31", "ZamGEQ31"},
     {"zamheadx2", "ZamHeadX2"},
     {"zammulticompx2", "com.zamaudio.zammulticompx2"},
     {"zamphono", "ZamPhono"},
     {"zamtube", "ZamTube"},
     {"zamulticomp", "ZaMultiComp"},
     {"zamverb", "ZamVerb"},
 }

 local menu4dbd6bf38858b519ac080da88da20042 = {
     {"Flashpoint Infinity", "/usr/lib/flashpoint-infinity/flashpoint-launcher ", "/usr/share/icons/hicolor/16x16/apps/flashpoint-launcher.png" },
     {"Mindustry", "/usr/bin/flatpak run --branch=stable --arch=x86_64 --command=mindustry.sh com.github.Anuken.Mindustry"},
     {"Minecraft Launcher", "minecraft-launcher"},
     {"Steam (Native)", "/usr/bin/steam-native ", "/usr/share/icons/hicolor/16x16/apps/steam.png" },
     {"Steam (Runtime)", "/usr/bin/steam-runtime ", "/usr/share/icons/hicolor/16x16/apps/steam.png" },
     {"mGBA", "mgba-qt ", "/usr/share/pixmaps/mgba.png" },
 }

 local menuaf8e527fa7389d550718563dbd09e634 = {
     {"Alacritty", "alacritty", "/usr/share/pixmaps/Alacritty.svg" },
     {"Android File Transfer (MTP)", "android-file-transfer"},
     {"Avahi Zeroconf Browser", "/usr/bin/avahi-discover"},
     {"Boxen", "gnome-boxes "},
     {"Discover", "plasma-discover ", "/usr/share/icons/hicolor/16x16/apps/plasmadiscover.png" },
     {"Druckerverwaltung", "/usr/bin/xdg-open http://localhost:631/", "/usr/share/icons/hicolor/16x16/apps/cups.png" },
     {"Farbprofilbetrachter", "gcm-viewer", "/usr/share/icons/hicolor/16x16/apps/gnome-color-manager.png" },
     {"Festplattenbelegungsanalyse", "baobab "},
     {"GParted", "/usr/bin/gparted ", "/usr/share/icons/hicolor/16x16/apps/gparted.png" },
     {"Hardware Locality lstopo", "lstopo"},
     {"Htop", "xterm -e htop", "/usr/share/pixmaps/htop.png" },
     {"KSysGuard", "ksysguard "},
     {"Konsole", "konsole"},
     {"LSHW", "/usr/sbin/gtk-lshw", "///usr/share/lshw/artwork/logo.svg" },
     {"LXTerminal", "lxterminal", "/usr/share/icons/hicolor/128x128/apps/lxterminal.png" },
     {"Massenumbenennen", "thunar --bulk-rename ", "/usr/share/icons/hicolor/16x16/apps/org.xfce.thunar.png" },
     {"OpenJDK Java 11 Console", "/usr/lib/jvm/java-11-openjdk/bin/jconsole", "/usr/share/icons/hicolor/16x16/apps/java11-openjdk.png" },
     {"OpenJDK Java 11 Shell", "xterm -e /usr/lib/jvm/java-11-openjdk/bin/jshell", "/usr/share/icons/hicolor/16x16/apps/java11-openjdk.png" },
     {"Oracle VM VirtualBox", "VirtualBox ", "/usr/share/icons/hicolor/16x16/mimetypes/virtualbox.png" },
     {"PCManFM Dateimanager", "pcmanfm "},
     {"Protokolle", "gnome-logs"},
     {"QTerminal herabhängend", "qterminal --drop"},
     {"Qterminal", "qterminal"},
     {"Sensorbetrachter", "xfce4-sensors", "/usr/share/icons/hicolor/24x24/apps/xfce-sensors.png" },
     {"Software", "gnome-software "},
     {"System installieren", "sh -c \"pkexec calamares\""},
     {"Systemmonitor", "plasma-systemmonitor"},
     {"Systemüberwachung", "gnome-system-monitor"},
     {"Taskmanager", "lxtask"},
     {"Taskmanager", "xfce4-taskmanager", "/usr/share/icons/hicolor/16x16/apps/org.xfce.taskmanager.png" },
     {"Terminal", "gnome-terminal"},
     {"Termite", "termite"},
     {"Thunar-Dateiverwaltung", "thunar ", "/usr/share/icons/hicolor/16x16/apps/org.xfce.thunar.png" },
     {"Tilix", "tilix"},
     {"Tint2", "tint2"},
     {"UXTerm", "uxterm", "/usr/share/pixmaps/xterm-color_48x48.xpm" },
     {"VMware Player", "/usr/bin/vmplayer ", "/usr/share/icons/hicolor/16x16/apps/vmware-player.png" },
     {"VMware Workstation", "/usr/bin/vmware ", "/usr/share/icons/hicolor/16x16/apps/vmware-workstation.png" },
     {"Virtual Network Editor", "/usr/bin/vmware-netcfg", "/usr/share/icons/hicolor/16x16/apps/vmware-netcfg.png" },
     {"Virtuelle Maschinenverwaltung", "virt-manager", "/usr/share/icons/hicolor/16x16/apps/virt-manager.png" },
     {"XTerm", "xterm", "/usr/share/pixmaps/xterm-color_48x48.xpm" },
     {"Xfce-Terminal", "xfce4-terminal", "/usr/share/icons/hicolor/16x16/apps/org.xfce.terminal.png" },
     {"dconf-Editor", "dconf-editor", "/usr/share/icons/hicolor/16x16/apps/ca.desrt.dconf-editor.png" },
     {"fish", "xterm -e fish", "/usr/share/pixmaps/fish.png" },
     {"nnn", "xterm -e nnn", "/usr/share/icons/hicolor/64x64/apps/nnn.png" },
 }

 local menu832f9901685a4e0cfef90f462339cb43 = {
     {"3BandEQ", "/usr/bin/3BandEQ"},
     {"3BandSplitter", "/usr/bin/3BandSplitter"},
     {"ADLMIDI", "xterm -e adlrt", "/usr/share/pixmaps/adljack.png" },
     {"ADLMIDI for Jack", "xterm -e adljack", "/usr/share/pixmaps/adljack.png" },
     {"ADLplug", "ADLplug", "/usr/share/icons/hicolor/32x32/apps/ADLplug.png" },
     {"Adobe Flash Player Standalone", "/usr/bin/flashplayer"},
     {"Agordejo", "agordejo", "/usr/share/icons/hicolor/16x16/apps/agordejo.png" },
     {"Agordejo Continue", "agordejo --continue --hide", "/usr/share/icons/hicolor/16x16/apps/agordejo.png" },
     {"AmplitudeImposer", "/usr/bin/AmplitudeImposer"},
     {"Ardour", "ardour6", "/usr/share/icons/hicolor/16x16/apps/ardour6.png" },
     {"Audacious", "audacious ", "/usr/share/icons/hicolor/48x48/apps/audacious.png" },
     {"Audacity", "env UBUNTU_MENUPROXY=0 audacity ", "/usr/share/icons/hicolor/16x16/apps/audacity.png" },
     {"Cadence", "cadence", "/usr/share/icons/hicolor/16x16/apps/cadence.png" },
     {"Calf Plugin Pack for JACK", "calfjackhost", "/usr/share/icons/hicolor/16x16/apps/calf.png" },
     {"Carla", "carla ", "/usr/share/icons/hicolor/16x16/apps/carla.png" },
     {"Carla Control", "carla-control ", "/usr/share/icons/hicolor/16x16/apps/carla-control.png" },
     {"Catia", "catia", "/usr/share/icons/hicolor/16x16/apps/catia.png" },
     {"Cheese", "cheese"},
     {"CsoundQt", "csoundqt "},
     {"CycleShifter", "/usr/bin/CycleShifter"},
     {"DIN Is Noise", "din", "/usr/share/pixmaps/din.png" },
     {"DeaDBeeF", "deadbeef ", "/usr/share/icons/hicolor/16x16/apps/deadbeef.png" },
     {"DragonflyEarlyReflections", "DragonflyEarlyReflections"},
     {"DragonflyHallReverb", "DragonflyHallReverb"},
     {"DragonflyPlateReverb", "DragonflyPlateReverb"},
     {"DragonflyRoomReverb", "DragonflyRoomReverb"},
     {"Drumstick Drum Grid", "drumstick-drumgrid", "/usr/share/icons/hicolor/16x16/apps/drumstick.png" },
     {"Drumstick MIDI Player", "drumstick-guiplayer ", "/usr/share/icons/hicolor/16x16/apps/drumstick.png" },
     {"Drumstick Virtual Piano", "drumstick-vpiano", "/usr/share/icons/hicolor/16x16/apps/drumstick.png" },
     {"EasyTAG", "easytag ", "/usr/share/icons/hicolor/16x16/apps/easytag.png" },
     {"Echomixer", "echomixer", "/usr/share/icons/hicolor/48x48/apps/echomixer.png" },
     {"Element", "element", "/usr/share/icons/hicolor/16x16/apps/net.kushview.element.png" },
     {"Envy24 Control", "envy24control", "/usr/share/icons/hicolor/48x48/apps/envy24control.png" },
     {"Fluajho", "fluajho", "/usr/share/icons/hicolor/16x16/apps/fluajho.png" },
     {"FoxDot", "FoxDot", "/usr/share/pixmaps/foxdot.png" },
     {"GNU Solfege", "solfege", "/usr/share/pixmaps/solfege.svg" },
     {"Geonkick", "env UBUNTU_MENUPROXY=0 geonkick ", "/usr/share/icons/hicolor/16x16/apps/geonkick.png" },
     {"Giada", "giada"},
     {"HDAJackRetask", "hdajackretask"},
     {"HDSPConf", "hdspconf", "/usr/share/icons/hicolor/48x48/apps/hdspconf.png" },
     {"HDSPMixer", "hdspmixer", "/usr/share/icons/hicolor/48x48/apps/hdspmixer.png" },
     {"Helm", "helm-synth", "/usr/share/icons/hicolor/16x16/apps/helm-synth.png" },
     {"Hwmixvolume", "hwmixvolume", "/usr/share/icons/hicolor/48x48/apps/hwmixvolume.png" },
     {"Hydrogen", "hydrogen "},
     {"JAPA", "japa"},
     {"JSampler Classic", "/usr/bin/jsampler classic", "/usr/share/pixmaps/jsampler-classic.png" },
     {"JSampler Fantasia", "/usr/bin/jsampler fantasia", "/usr/share/pixmaps/jsampler.png" },
     {"Jack Mixer", "jack_mixer", "/usr/share/icons/hicolor/16x16/apps/jack_mixer.png" },
     {"Kars", "/usr/bin/Kars"},
     {"Kwave-Sound-Editor", "kwave "},
     {"LMMS", "lmms ", "/usr/share/icons/hicolor/16x16/apps/lmms.png" },
     {"LXMusic simple music player", "lxmusic", "/usr/share/icons/hicolor/128x128/apps/lxmusic.png" },
     {"Luppp", "luppp", "/usr/share/pixmaps/luppp.png" },
     {"MVerb", "/usr/bin/MVerb"},
     {"MaBitCrush", "/usr/bin/MaBitCrush"},
     {"MaFreeverb", "/usr/bin/MaFreeverb"},
     {"MaGigaverb", "/usr/bin/MaGigaverb"},
     {"MaPitchshift", "/usr/bin/MaPitchshift"},
     {"Mixxx", "sh -c \"pasuspender -- mixxx -platform xcb || mixxx -platform xcb\"", "/usr/share/pixmaps/mixxx_icon.svg" },
     {"MusE", "muse4", "/usr/share/icons/hicolor/64x64/apps/muse.png" },
     {"MuseScore 3.6", "mscore ", "/usr/share/icons/hicolor/16x16/apps/mscore.png" },
     {"Musik", "gnome-music"},
     {"Nekobi", "/usr/bin/Nekobi"},
     {"New Session Manager (Legacy GUI)", "nsm-legacy-gui"},
     {"Ninjas2", "ninjas2"},
     {"Non Mixer", "/usr/bin/non-mixer", "/usr/share/icons/hicolor/16x16/apps/non-mixer.png" },
     {"Non Sequencer", "/usr/bin/non-sequencer", "/usr/share/icons/hicolor/16x16/apps/non-sequencer.png" },
     {"Non Timeline", "/usr/bin/non-timeline", "/usr/share/icons/hicolor/16x16/apps/non-timeline.png" },
     {"OBS Studio", "obs", "/usr/share/icons/hicolor/256x256/apps/com.obsproject.Studio.png" },
     {"OPNplug", "OPNplug", "/usr/share/icons/hicolor/32x32/apps/OPNplug.png" },
     {"OpenShot Video Editor", "openshot-qt ", "/usr/share/icons/hicolor/64x64/apps/openshot-qt.png" },
     {"Parole-Medienspieler", "parole ", "/usr/share/icons/hicolor/16x16/apps/org.xfce.parole.png" },
     {"PatchMatrix", "/usr/bin/patchmatrix", "/usr/share/icons/hicolor/256x256/apps/patchmatrix.png" },
     {"Patroneo", "patroneo", "/usr/share/icons/hicolor/16x16/apps/patroneo.png" },
     {"PingPongPan", "/usr/bin/PingPongPan"},
     {"Polyphone", "polyphone "},
     {"ProM", "/usr/bin/ProM"},
     {"PulseAudio System Tray", "pasystray", "/usr/share/pixmaps/pasystray.png" },
     {"PulseAudio Volume Control", "pavucontrol-qt"},
     {"PulseAudio-Lautstärkeregler", "pavucontrol"},
     {"Pure Data", "pd", "/usr/share/icons/hicolor/16x16/apps/pd.png" },
     {"QMidiArp", "qmidiarp "},
     {"QMidiRoute", "qmidiroute"},
     {"QXGEdit", "qxgedit", "/usr/share/icons/hicolor/32x32/apps/qxgedit.png" },
     {"QasConfig", "qasconfig", "/usr/share/icons/hicolor/16x16/apps/qasconfig.png" },
     {"QasHctl", "qashctl", "/usr/share/icons/hicolor/16x16/apps/qashctl.png" },
     {"QasMixer", "qasmixer", "/usr/share/icons/hicolor/16x16/apps/qasmixer.png" },
     {"QjackCtl", "qjackctl", "/usr/share/icons/hicolor/32x32/apps/qjackctl.png" },
     {"QmidiCtl", "qmidictl"},
     {"QmidiNet", "qmidinet", "/usr/share/icons/hicolor/32x32/apps/qmidinet.png" },
     {"Qsampler", "qsampler ", "/usr/share/icons/hicolor/32x32/apps/qsampler.png" },
     {"Qsynth", "qsynth", "/usr/share/icons/hicolor/32x32/apps/qsynth.png" },
     {"Qt V4L2 test Utility", "qv4l2", "/usr/share/icons/hicolor/16x16/apps/qv4l2.png" },
     {"Qt V4L2 video capture utility", "qvidcap", "/usr/share/icons/hicolor/16x16/apps/qvidcap.png" },
     {"Qtractor", "qtractor ", "/usr/share/icons/hicolor/32x32/apps/qtractor.png" },
     {"Rosegarden", "rosegarden ", "/usr/share/icons/hicolor/16x16/apps/rosegarden.png" },
     {"Sonic Pi", "sonic-pi", "/usr/share/pixmaps/sonic-pi.png" },
     {"Sonic Visualiser", "sonic-visualiser "},
     {"SoulForce", "/usr/bin/SoulForce"},
     {"SpectMorph Jack Client", "smjack ", "/usr/share/pixmaps/smjack.png" },
     {"SuperCollider IDE", "scide ", "/usr/share/pixmaps/sc_ide.svg" },
     {"Sweep", "sweep", "/usr/share/pixmaps/sweep.svg" },
     {"Tonaufzeichner", "gnome-sound-recorder"},
     {"VLC Media Player", "/usr/bin/vlc --started-from-file ", "/usr/share/icons/hicolor/16x16/apps/vlc.png" },
     {"VMPK", "vmpk", "/usr/share/icons/hicolor/16x16/apps/vmpk.png" },
     {"Vico", "vico", "/usr/share/icons/hicolor/16x16/apps/vico.png" },
     {"Videos", "totem "},
     {"Volume Icon", "volumeicon"},
     {"Wolf-spectrum", "wolf-spectrum"},
     {"Xfburn", "xfburn"},
     {"YASS", "yass"},
     {"Yoshimi", "yoshimi", "/usr/share/pixmaps/yoshimi.png" },
     {"ZynAddSubFX - Alsa", "zynaddsubfx -I alsa -O alsa", "/usr/share/pixmaps/zynaddsubfx.svg" },
     {"ZynAddSubFX - Jack", "zynaddsubfx -I jack -O jack", "/usr/share/pixmaps/zynaddsubfx.svg" },
     {"ZynAddSubFX - Jack (multi channel)", "zynaddsubfx -I jack -O jack-multi", "/usr/share/pixmaps/zynaddsubfx.svg" },
     {"ZynAddSubFX - OSS", "zynaddsubfx -I OSS -O OSS", "/usr/share/pixmaps/zynaddsubfx.svg" },
     {"aliki", "aliki"},
     {"ambdec", "ambdec"},
     {"ambix_binaural", "ambix_binaural"},
     {"ambix_converter", "ambix_converter"},
     {"ambix_decoder", "ambix_decoder"},
     {"ambix_directional_loudness", "ambix_directional_loudness"},
     {"ambix_encoder", "ambix_encoder"},
     {"ambix_mirror", "ambix_mirror"},
     {"ambix_rotator", "ambix_rotator"},
     {"ambix_vmic", "ambix_vmic"},
     {"ams", "ams", "/usr/share/pixmaps/ams_32.xpm" },
     {"amsynth", "/usr/bin/amsynth", "/usr/share/icons/hicolor/48x48/apps/amsynth.png" },
     {"drumkv1", "drumkv1_jack", "/usr/share/icons/hicolor/32x32/apps/drumkv1.png" },
     {"ebumeter", "ebumeter"},
     {"gigedit", "gigedit"},
     {"glBars", "/usr/bin/glBars"},
     {"guitarix", "guitarix", "/usr/share/pixmaps/gx_head.png" },
     {"mpv Media Player", "mpv --player-operation-mode=pseudo-gui -- ", "/usr/share/icons/hicolor/16x16/apps/mpv.png" },
     {"padthv1", "padthv1_jack", "/usr/share/icons/hicolor/32x32/apps/padthv1.png" },
     {"samplv1", "samplv1_jack", "/usr/share/icons/hicolor/32x32/apps/samplv1.png" },
     {"setBfree", "setBfreeUI", "/usr/share/pixmaps/setBfree.png" },
     {"snd", "snd"},
     {"ssr", "ssr"},
     {"ssr-aap", "ssr-aap"},
     {"ssr-binaural", "ssr-binaural"},
     {"ssr-brs", "ssr-brs"},
     {"ssr-dca", "ssr-dca"},
     {"ssr-generic", "ssr-generic"},
     {"ssr-vbap", "ssr-vbap"},
     {"ssr-wfs", "ssr-wfs"},
     {"synthv1", "synthv1_jack", "/usr/share/icons/hicolor/32x32/apps/synthv1.png" },
     {"wolf-shaper", "wolf-shaper"},
     {"x42-whirl", "x42-whirl", "/usr/share/pixmaps/x42-whirl.png" },
     {"zamgrains", "ZamGrains"},
     {"zita-at1", "zita-at1"},
     {"zita-bls1", "zita-bls1"},
     {"zita-dc1", "zita-dc1"},
     {"zita-dpl1", "zita-dpl1"},
     {"zita-mu1", "zita-mu1"},
     {"zita-rev1", "zita-rev1"},
 }

 local menuf022205808b7868110a5722844a76ab7 = {
     {"Albert", "albert"},
     {"Anwendungsfinder", "xfce4-appfinder", "/usr/share/icons/hicolor/16x16/apps/org.xfce.appfinder.png" },
     {"Archivverwaltung", "file-roller "},
     {"Azote", "azote", "/usr/share/pixmaps/azote.svg" },
     {"Bildbetrachter", "gpicview ", "/usr/share/icons/hicolor/48x48/apps/gpicview.png" },
     {"Bildschirmfoto", "gnome-screenshot --interactive"},
     {"Bildschirmfoto", "xfce4-screenshooter", "/usr/share/icons/hicolor/16x16/apps/org.xfce.screenshooter.png" },
     {"Bücher", "gnome-books"},
     {"Catarina", "catarina", "/usr/share/icons/hicolor/16x16/apps/catarina.png" },
     {"Code - OSS", "/usr/bin/code-oss --no-sandbox --unity-launch ", "/usr/share/pixmaps/com.visualstudio.code.oss.png" },
     {"Dateien", "nautilus --new-window "},
     {"Karten", "gapplication launch org.gnome.Maps "},
     {"Klipper", "klipper"},
     {"Kupfer", "kupfer ", "/usr/share/icons/hicolor/22x22/apps/kupfer.png" },
     {"Kvantum Manager", "kvantummanager"},
     {"LXQt Archiver", "lxqt-archiver "},
     {"Latte", "/usr/bin/latte-dock", "/usr/share/icons/hicolor/16x16/apps/latte-dock.svg" },
     {"Laufwerke", "gnome-disks"},
     {"Launchy", "launchy ", "/usr/share/pixmaps/launchy_icon.png" },
     {"MATE-Schriftanzeiger", "mate-font-viewer "},
     {"Marker", "marker "},
     {"Micro", "xterm -e micro "},
     {"Minder", "com.github.phase1geo.minder ", "/var/lib/flatpak/exports/share/icons/hicolor/16x16/apps/com.github.phase1geo.minder.svg" },
     {"Mousepad", "mousepad ", "/usr/share/icons/hicolor/16x16/apps/org.xfce.mousepad.png" },
     {"Neovide (nvim)", "neovide ", "/usr/share/pixmaps/nvim.png" },
     {"Neovim", "xterm -e nvim ", "/usr/share/pixmaps/nvim.png" },
     {"Neovim-Qt", "nvim-qt -- ", "/usr/share/icons/hicolor/192x192/apps/nvim-qt.png" },
     {"Onboard", "onboard", "/usr/share/icons/hicolor/16x16/apps/onboard.png" },
     {"PCManFM-Qt", "pcmanfm-qt "},
     {"Plank", "plank", "/usr/share/icons/hicolor/16x16/apps/plank.svg" },
     {"PlayOnLinux", "playonlinux ", "/usr/share/pixmaps/playonlinux.png" },
     {"Schriften", "gnome-font-viewer "},
     {"Taschenrechner", "gnome-calculator"},
     {"Texteditor", "gedit "},
     {"Uhren", "gnome-clocks"},
     {"Ulauncher", "env GDK_BACKEND=x11 /usr/bin/ulauncher --hide-window", "/usr/share/icons/hicolor/48x48/apps/ulauncher.svg" },
     {"VSCodium", "/usr/share/vscodium-bin/bin/codium --no-sandbox --unity-launch ", "/usr/share/pixmaps/vscodium.png" },
     {"Verbindungen", "gnome-connections"},
     {"Vim", "xterm -e vim ", "/usr/share/icons/hicolor/48x48/apps/gvim.png" },
     {"Wetter", "gapplication launch org.gnome.Weather"},
     {"Winetricks", "winetricks --gui"},
     {"Xarchiver", "xarchiver ", "/usr/share/icons/hicolor/16x16/apps/xarchiver.png" },
     {"Xfburn", "xfburn"},
     {"Zeichen", "/usr/bin/gnome-characters"},
     {"Zeichentabelle", "gucharmap"},
     {"ipython", "xterm -e ipython", "/usr/share/pixmaps/ipython.png" },
     {"nitrogen", "nitrogen", "/usr/share/icons/hicolor/16x16/apps/nitrogen.png" },
     {"pentablet", "/usr/lib/pentablet/pentablet.sh", "///usr/share/icons/pentablet.png" },
 }

xdgmenu = {
    {"Barrierefreiheit", menub98be87cb7dd79b1aae28d118dbf9f72},
    {"Bildung", menud51ff67768edbb1ac85d6f654b29a1f1},
    {"Büro", menu63909e8219db0bcede147cb7926a07fa},
    {"Entwicklung", menu9356bc29cbd145b1b330eaeb7614fd1e},
    {"Grafik", menue64b29f9c504872c202fabd746ddbf8a},
    {"Internet", menuc8205c7636e728d448c2774e6a4a944b},
    {"Sonstige", menu1c312514bc584128c5392d361470b415},
    {"Spiele", menu4dbd6bf38858b519ac080da88da20042},
    {"Systemwerkzeuge", menuaf8e527fa7389d550718563dbd09e634},
    {"Unterhaltungsmedien", menu832f9901685a4e0cfef90f462339cb43},
    {"Zubehör", menuf022205808b7868110a5722844a76ab7},
}

